#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "traccar"
name = "Traccar"
description.en = "GPS tracking platform"
description.fr = "Plateforme de suivi GPS"

version = "5.9~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "Apache-2.0"
website = "https://www.traccar.org/"
demo = "https://www.traccar.org/demo-server/"
admindoc = "https://www.traccar.org/documentation/"
code = "https://some.forge.com/example/example"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/traccar/traccar/releases/download/v5.9/traccar-other-5.9.zip"
        sha256 = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "mariadb-server, openjdk-11-jre-headless "

    [resources.database]
    type = "mysql"
